# Site settings
title: "Kali Linux Attack Techniques"
description: "A collection of Kali Linux attack techniques for penetration testing."
baseurl: ""  # Leave empty for the root or set it if it's hosted in a subfolder like /project.
url: "https://jas0n0ss.github.io/kali"  # Replace with your GitHub Pages URL

# GitHub Pages and theme setup
remote_theme: pages-themes/hacker@v0.2.0  # Changed to the Hacker theme
markdown: kramdown

# Navigation and other configurations
navbar:
  - text: "Home"
    url: "/index.md"
  - text: "Backdoor Attacks"
    url: "/kali-backdoor"
  - text: "Server Attacks"
    url: "/kali-server-attack"
  - text: "Web Attacks"
    url: "/kali-web-attack"

# Author settings
author:
  bio: "Cybersecurity enthusiast and Kali Linux practitioner."

# Pagination settings (optional)
paginate: 5

# Exclude specific files or directories from being processed
exclude:
  - README.md

# Jekyll plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Your Name"
