title: "Kali Linux Attack Techniques"
email: your-email@example.com
description: "A collection of Kali Linux attack techniques for penetration testing."
baseurl: ""  # Leave empty for the root or set it if it's hosted in a subfolder like /project.
url: "https://username.github.io/kali-attacks"  # Replace with your GitHub Pages URL

# GitHub Pages and theme setup
theme: cayman
markdown: kramdown

# Optional: Set up your navigation links and other custom settings below
navbar:
  - text: "Home"
    url: "/index.md"
  - text: "Backdoor Attacks"
    url: "/kali-backdoor/"
  - text: "Server Attacks"
    url: "/kali-server-attack/"
  - text: "Web Attacks"
    url: "/kali-web-attack/"
  - text: "Images"
    url: "/imgs/"

social_links:
  - icon: "github"
    url: "https://github.com/username"
  - icon: "twitter"
    url: "https://twitter.com/username"

author:
  name: "Your Name"
  bio: "Cybersecurity enthusiast and Kali Linux practitioner."

# Google Analytics (optional)
google_analytics: UA-XXXXX-Y

# Pagination settings (optional)
paginate: 5

# Exclude specific files or directories from being processed
exclude:
  - README.md
  - LICENSE

# Jekyll plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Your Name"
