title: Kali 技术文档合集
description: Kali 后门、服务器攻击与 Web 攻击技术文档
remote_theme: just-the-docs/just-the-docs
baseurl: "/kali"
url: "https://jas0n0ss.github.io"

# 侧边栏导航结构
nav:
  - title: 后门技术
    url: /kali-backdoor/
    children:
      - title: 01维持访问的基本思路介绍
        url: /kali-backdoor/01维持访问的基本思路介绍
      - title: 02Metasploit创建WebShell
        url: /kali-backdoor/02Metasploit创建WebShell
      - title: 03使用sbd及dbd创建系统安全后门
        url: /kali-backdoor/03使用sbd及dbd创建系统安全后门
      - title: 04PowerSploit创建Windows后门
        url: /kali-backdoor/04PowerSploit创建Windows后门
      - title: 05Backdoor-factory向程序中植入木马
        url: /kali-backdoor/05Backdoor-factory向程序中植入木马
      - title: 06DNS2TCP在DNS数据流中维持TCP连接的原理
        url: /kali-backdoor/06DNS2TCP在DNS数据流中维持TCP连接的原理
      - title: 07Linux环境下向程序中注入后门代码
        url: /kali-backdoor/07Linux环境下向程序中注入后门代码
      - title: 08使用Weevely创建PHP挂马文件
        url: /kali-backdoor/08使用Weevely创建PHP挂马文件
      - title: 09PWNAT创建NAT-NAT通信隧道
        url: /kali-backdoor/09PWNAT创建NAT-NAT通信隧道
      - title: 10weBaCoo创建php木马后门
        url: /kali-backdoor/10weBaCoo创建php木马后门
  - title: 服务器攻击
    url: /kali-server-attack/
    children:
      - title: 01Kali实验环境介绍与使用
        url: /kali-server-attack/01Kali实验环境介绍与使用
      - title: 02一次简单的渗透测试实战
        url: /kali-server-attack/02一次简单的渗透测试实战
      - title: 03使用多种安全工具获取目标主机信息
        url: /kali-server-attack/03使用多种安全工具获取目标主机信息
      - title: 04Metasploit基础知识和使用
        url: /kali-server-attack/04Metasploit基础知识和使用
      - title: 05Nmap配合Metasploit进行端口扫描
        url: /kali-server-attack/05Nmap配合Metasploit进行端口扫描
      - title: 06扫描目标主机网络服务安全漏洞
        url: /kali-server-attack/06扫描目标主机网络服务安全漏洞
      - title: 07Kali常用漏洞扫描工具实战
        url: /kali-server-attack/07Kali常用漏洞扫描工具实战
      - title: 08开发新的Metasploit扫描器
        url: /kali-server-attack/08开发新的Metasploit扫描器
      - title: 09攻击Ingreslock后门漏洞
        url: /kali-server-attack/09攻击Ingreslock后门漏洞
      - title: 10Samba漏洞攻击Linux服务器
        url: /kali-server-attack/10Samba漏洞攻击Linux服务器
      - title: 11攻击UnrealIrcd服务
        url: /kali-server-attack/11攻击UnrealIrcd服务
      - title: 12暴力破解SSH及VNC远程连接
        url: /kali-server-attack/12暴力破解SSH及VNC远程连接
      - title: 13攻击Distcc获取权限
        url: /kali-server-attack/13攻击Distcc获取权限
      - title: 14目标Linux服务器提权
        url: /kali-server-attack/14目标Linux服务器提权
      - title: 15攻击Tomcat漏洞
        url: /kali-server-attack/15攻击Tomcat漏洞
      - title: 16利用NFS错误配置进行攻击
        url: /kali-server-attack/16利用NFS错误配置进行攻击
      - title: 17利用FTP服务漏洞进行攻击
        url: /kali-server-attack/17利用FTP服务漏洞进行攻击
      - title: 18利用Telnet服务漏洞进行攻击
        url: /kali-server-attack/18利用Telnet服务漏洞进行攻击
      - title: 19创建包含Windows后门的PDF文件
        url: /kali-server-attack/19创建包含Windows后门的PDF文件
      - title: 20攻击后清除痕迹并创建访问后门
        url: /kali-server-attack/20攻击后清除痕迹并创建访问后门
  - title: Web 攻击
    url: /kali-web-attack/
    children:
      - title: 01Kali实验环境介绍与使用
        url: /kali-web-attack/01Kali实验环境介绍与使用
      - title: 02发现Web漏洞的方法
        url: /kali-web-attack/02发现Web漏洞的方法
      - title: 03BeEF攻击实战
        url: /kali-web-attack/03BeEF攻击实战
      - title: 04反射型跨站脚本XSS攻击
        url: /kali-web-attack/04反射型跨站脚本XSS攻击
      - title: 05存储型跨站脚本XSS攻击
        url: /kali-web-attack/05存储型跨站脚本XSS攻击
      - title: 06SQL注入
        url: /kali-web-attack/06SQL注入
      - title: 07SQL注入（Blind）
        url: /kali-web-attack/07SQL注入（Blind）
      - title: 08本地文件包含
        url: /kali-web-attack/08本地文件包含
      - title: 09远程文件包含
        url: /kali-web-attack/09远程文件包含
      - title: 10Metasploit渗透攻击Web服务
        url: /kali-web-attack/10Metasploit渗透攻击Web服务
      - title: 11Web弱密码暴力破解
        url: /kali-web-attack/11Web弱密码暴力破解
      - title: 12跨站请求伪造（CSRF）
        url: /kali-web-attack/12跨站请求伪造（CSRF）
      - title: 13Kali命令注入攻击
        url: /kali-web-attack/13Kali命令注入攻击
      - title: 14验证码安全问题
        url: /kali-web-attack/14验证码安全问题
      - title: 15拒绝服务攻击（DoS）
        url: /kali-web-attack/15拒绝服务攻击（DoS）
      - title: 16Ajax安全问题
        url: /kali-web-attack/16Ajax安全问题
      - title: 17Web会话劫持
        url: /kali-web-attack/17Web会话劫持
      - title: 18使用Metasploit攻击IE浏览器漏洞
        url: /kali-web-attack/18使用Metasploit攻击IE浏览器漏洞
      - title: 19Webshell访问后门
        url: /kali-web-attack/19Webshell访问后门
      - title: 20如何避免Web安全漏洞
        url: /kali-web-attack/20如何避免Web安全漏洞

just_the_docs:
  custom_css:
    - assets/css/custom.css